repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^(experiments/|sbatch/|.*\.md|scripts/)
      - id: trailing-whitespace
        exclude: ^(experiments/|sbatch/|.*\.md|scripts/)
      - id: detect-private-key
        exclude: ^(experiments/|sbatch/|scripts/)
      - id: debug-statements
        exclude: ^(experiments/|sbatch/|scripts/)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^(experiments/|sbatch/|scripts/)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(exp/|sbatch/|.*\.md|scripts/)
        args: ["--profile", "black", "--src", "policy_extraction", "--src", "exp"]
